### ISSUE TITLE
Streams unpause on tab change

### ISSUE THREAD

**Issue by saucettv** [saucettv/VideoAdBlockForTwitch#34]
To be fixed in next version.

**Comment by saucettv** [comment]
Fixed in 5.3.2

**Comment by kapistelijaJami** [comment]
I still have this issue in version 5.3.2 in chrome. If I change a tab in the same window it will continue playing. It will usually do it at least twice per tab change (pause-unpause, pause-unpause).
